Project init
codex-team/devops-toolbox-api pull request #1
Opened 2020-10-22 09:48 UTC by kebyo

2020-10-22 14:55 UTC, nikmel2803 commented on package.json
> +    "@types/express": "^4.17.8"
это будет нужно не только для разработки, так что надо поместить в секцию dependencies

2020-10-22 14:55 UTC, nikmel2803 commented on src/index.ts
> +    console.log(`⚡️[server]: Server is running at https://localhost:${PORT}`);
```suggestion
    console.log(`⚡️[server]: Server is running at http://localhost:${PORT}`);
```

2020-10-22 15:09 UTC, neSpecc requested changes

2020-10-22 15:09 UTC, neSpecc commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.0.1",
```

2020-10-22 15:09 UTC, neSpecc commented on package.json
> +  "license": "ISC",
```suggestion
  "license": "unlicensed",
```

2020-10-22 15:09 UTC, neSpecc commented on package.json
> +  "author": "CodeX Team",
```suggestion
  "author": "CodeX",
```

2020-10-22 15:09 UTC, neSpecc commented on src/index.ts
> +const PORT = 3000;
порт надо вынести в env

2020-10-22 18:09 UTC, neSpecc commented on .env.example
> +PORT =
```suggestion
PORT=3000 
```

2020-10-22 18:09 UTC, neSpecc commented on src/config/config.ts
> +class Config {
надо описать класс в jsdoc

2020-10-23 11:11 UTC, neSpecc approved these changes

2020-10-23 20:19 UTC, nikmel2803 approved these changes

2020-10-23 20:25 UTC, merged