Feature/client update after db update
codex-team/devops-toolbox-api pull request #10
Opened 2020-11-09 10:00 UTC by kebyo

1. Создал класс для того, чтобы хранить клиентов
2. Добавил отправку обновленного воркспейса клиенту

2020-11-10 12:48 UTC, neSpecc commented on src/index.ts
> +const clients: Clients = new Clients();
не описано

2020-11-10 12:48 UTC, neSpecc commented on src/types/client.ts
> + * Interface for client
непонятное описание

2020-11-10 12:49 UTC, neSpecc commented on src/controllers/agent.ts
> +      const client: ws = clients.find(workspace.authToken);
тут не authToken должен быть, а интеграционный

2020-11-10 15:05 UTC, kebyo commented on src/controllers/agent.ts
> +      const client: ws = clients.find(workspace.authToken);
messageId?

2020-11-11 08:49 UTC, kebyo commented on src/controllers/agent.ts
> +      const client: ws = clients.find(workspace.authToken);
А как мне делать соответствие  между сокетом и интеграционным токеном? Парсить конфиг или как-то передавать в заголовке интеграционные токены при подключении клиента к серверу?

2020-11-11 13:52 UTC, neSpecc commented on src/index.ts
> +    authToken: req.headers.authorization!,
я думаю, где-то тут должна происходить проверка авторизации по заголовку и получение из базы (или конфига) воркспейса по authToken. Далее в Client передавать уже workspace._id

2020-11-12 15:59 UTC, nikmel2803 requested changes

2020-11-12 15:59 UTC, nikmel2803 commented on docs/routes.md
> +#Routes
```suggestion
# Routes
```

2020-11-12 15:59 UTC, nikmel2803 commented on src/controllers/agent.ts
> +      const client: ws = clients.find(workspace.authToken);
Петя ответил ниже
Ещё тут есть проблема в том, что у тебя может быть несколько клиентов, получающих данные об одном воркспейсе, а тут у тебя используется find, которые возвращает лишь одного клиента
надо использовать filter и потом отправлять данные массиву клиентов

2020-11-12 15:59 UTC, nikmel2803 commented on src/index.ts
> +export { clients };
Как-то не очень экспортировать тут что-то
1) можно сделать Clients синглтоном
2) можно инициализировать тут Clients и прокидывать этот объект либо res.locals или сделать поле context в Request

2020-11-12 15:59 UTC, nikmel2803 commented on src/utils/clients.ts
> +  private clients: { [key: string]: ws};
тут не описано
ещё можно вместо `{ [key: string]: ws}` написать `Record<string, ws>`

2020-11-12 15:59 UTC, nikmel2803 commented on src/utils/clients.ts
> +  private clients: { [key: string]: ws};
а ещё написать = {} и убрать конструктор тогда

2020-11-12 15:59 UTC, nikmel2803 commented on src/utils/clients.ts
> +  public find(authToken: string): ws {
как я написал выше, тут надо переделать, потому что по одному токену может быть несколько клиентов

2020-11-14 14:02 UTC, neSpecc requested changes

2020-11-14 14:02 UTC, neSpecc commented on src/utils/clients.ts
> +  private static singleTone: Clients;
не описаны свойства

2020-11-14 14:02 UTC, neSpecc commented on src/utils/clients.ts
> + * Clients class
непонятное описание

2020-11-14 17:52 UTC, nikmel2803 approved these changes

2020-11-14 17:52 UTC, nikmel2803 commented on src/index.ts
> +  const workspaces: Workspace[] | null = await WorkspacesService.find({ authToken });
типы указывать тут не надо
они ни к чему, TS и так понимает всё

2020-11-14 18:08 UTC, neSpecc commented on src/index.ts
> +    console.log('Error authorization');
и соединение надо закрыть

2020-11-16 17:46 UTC, neSpecc requested changes

2020-11-16 17:46 UTC, neSpecc commented on docs/routes.md
> +* **POST** - Добавляет воркспейс в БД
почему воркспейс добавляет `post /services`, а не `post /workspace` ?

2020-11-16 17:46 UTC, neSpecc commented on docs/routes.md
> +                            "smth": "smth"
а структура payload где-то задокументирована?

2020-11-16 17:46 UTC, neSpecc commented on src/controllers/agent.ts
> +      clients?.forEach(client => client.socket.send(JSON.stringify(workspace)));
не понимаю эту строку. Тут просто в сокеты отправляется воркспейс. У нас же в сообщении должен быть messageId, type и payload. Как клиент поймет что это такое пришло?

2020-11-16 17:46 UTC, neSpecc commented on src/controllers/agent.ts
> +    res.json({
тоже не понятная структура объекта. Это что за интерфейс? Нужно указать тип

2020-11-16 17:46 UTC, neSpecc commented on src/index.ts
> +  const clients: Clients = Clients.getClients();
не описаны константы

2020-11-16 17:46 UTC, neSpecc commented on src/index.ts
> +  const workspaces: Workspace[] | null = await WorkspacesService.find({ authToken });
не исправлено

2020-11-16 17:46 UTC, neSpecc commented on src/index.ts
> +    socket.close(1007);
magic number

2020-11-16 17:46 UTC, neSpecc commented on src/routes/services.ts
> +router.post('/', AgentController.addWorkspace);
не относится к сервисам

2020-11-16 17:46 UTC, neSpecc commented on src/types/client.ts
> +   * Client workspaces
написано что это воркспейсы, а тип string[]

2020-11-16 17:46 UTC, neSpecc commented on src/types/client.ts
> +  workspaces: string[];
если это айдишники, то поле надо назвать workspaceIds

2020-11-16 17:46 UTC, neSpecc commented on src/utils/clients.ts
> +  private static singleTone: Clients;
обычно называют instance

2020-11-16 17:58 UTC, neSpecc commented on src/utils/clients.ts
> +class Clients {
еще не очень нравится название сущности во множественном числе. Все таки класс представляет что-то одно. Может назвать ClientsList или ConnectedClientsList например или что-то типа того. А то путаница между Client и Clients.

2020-11-16 17:58 UTC, neSpecc commented on src/index.ts
> +    clients.remove(socket);
также нужно удалять клиента в обработчике onerror

2020-11-17 14:52 UTC, kebyo commented on docs/routes.md
> +* **POST** - Добавляет воркспейс в БД
У меня не работал скрипт Кости initDb.ts и я это добавил, чтобы тестить. Может это не нужно вообще?

2020-11-17 14:55 UTC, kebyo commented on docs/routes.md
> +                            "smth": "smth"
Ну она зависит от типа сервиса. Где-то массив объектов, а где-то один объект. Я не стал более подробный запрос делать для примера, потому что там была какая-то инфа по серверу Кодекса. Подумал, что наверное не стоит это показывать.

2020-11-17 15:08 UTC, kebyo commented on src/controllers/agent.ts
> +      clients?.forEach(client => client.socket.send(JSON.stringify(workspace)));
А какой тогда будет messageId, если клиент не делает запрос? Это сообщение отправляется тогда, когда делается запрос от агента.

2020-11-17 17:21 UTC, neSpecc commented on docs/routes.md
> +* **POST** - Добавляет воркспейс в БД
да, это пока не нужно. Давай удалим

2020-11-17 17:21 UTC, neSpecc commented on src/controllers/agent.ts
> +      clients?.forEach(client => client.socket.send(JSON.stringify(workspace)));
`messageId` будет `null`. Так клиент поймет, что это не response, а сообщение, инициированное апи.  А `type` будет `workspace-update`. Так клиент поймет, как обработать payload.

2020-11-17 21:35 UTC, neSpecc requested changes

2020-11-17 21:35 UTC, neSpecc commented on src/types/response.ts
> +interface Response {
не совсем корректное название. У `response` нету поля `type`. Это лучше назвать `Message`. А еще лучше сделать отдельные интерфейсы:

```ts
/**
 * Message can contain any data at payload
 */
export type MessagePayload = object;

/**
 * Any client-server message should fit this structure
 */
interface Message {
  payload: MessagePayload;
}

/**
 * Messages from the API sent in response to some client's message
 */
interface ResponseMessage extends Message {
   messageId: string; // <-- потом перенесем это в Message. По-хорошему, API тоже должен генерировать id сообщения, чтобы клиент мог на него ответить. 
}

/**
 * Message that initiated by the API
 */
interface OutgoingMessage extends Message {
  type: string;
}
```

2020-11-17 21:35 UTC, neSpecc commented on src/controllers/agent.ts
> +      const wsResponse: Response = {
тут все еще не идеально: формирование сообщений должно быть где-то в одном месте. В классе, отвечающем за транспортный уровень. А сейчас у нас они формируются, по сути, хардкодом в разных местах (`controllers/agent.ts`, `controllers/workspace.ts`, `src/index.ts`).

Подумай, куда можно это вынести

2020-11-17 21:35 UTC, neSpecc commented on src/controllers/workspaces.ts
> +    res.json({
вот тут тоже ответ не соответствует протоколу

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +   * Current connected clients
```suggestion
   * Currently connected clients
```

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +   * Connecting client authorization token
```suggestion
   * Connected client's authorization token
```

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +   * Connecting client workspaces
```suggestion
   * Connected client's workspaces list
```

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +   * Error
```suggestion
   * Sockets error handler 
```

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +   * Сlient disconnects
```suggestion
   * Сlient disconnecting handler
```

2020-11-17 21:35 UTC, neSpecc commented on src/index.ts
> +    socket.send('Error authorization');
ответ не соответствует нашему протоколу. Думаю, он тут вообще не нужен, кода достаточно

2020-11-17 21:36 UTC, neSpecc commented on src/types/response.ts
> +interface Response {
ну и `IncomingMessage` надо сделать еще

2020-11-19 13:10 UTC, kebyo commented on src/types/response.ts
> +interface Response {
1. А почему API должен генерировать id сообщения? Мы разве не используем id сообщения, который нам пришел? Как клиент поймет, по другому id сообщения, что это конкретный "ответ" на его конкретный "запрос"?
2. Зачем клиенту отвечать на сообщения от API?

2020-11-19 13:16 UTC, neSpecc commented on src/types/response.ts
> +interface Response {
1. Это только в случае `OutgoingMessage`, когда сообщение инициирует сам бэкенд
2. Например, в следующих версиях протокола может появиться подтверждение получения сообщений. То есть когда клиент получает сообщение, он должен отправить в ответ `ack` с `id` этого сообщения. В противном случае, бэкенд будет слать это сообщение повторно, пока не получит `ack`. Так, например, работает API Telegram. Это нужно для гарантии доставки сообщений, даже при проблемах с интернетом.

2020-11-19 17:01 UTC, neSpecc requested changes

2020-11-19 17:01 UTC, neSpecc commented on src/utils/server.ts
> +export default class Server {
Почему сервер? Давай назовем этот класс Transport. 

и я бы положил его (и типы, связанные с ним) в папку `/utils/protocol/`. В будущем его можно будет вынести в отдельный npm-пакет и использовать в других проектах

2020-11-19 17:01 UTC, neSpecc commented on src/utils/server.ts
> +  public static async connection(socket: ws, req: express.Request): Promise<void> {
почему все через статик?

2020-11-19 17:01 UTC, neSpecc commented on src/types/outgoingMessage.ts
> +interface OutgoingMessage extends Message {
не описано

2020-11-19 17:01 UTC, neSpecc commented on src/types/message.ts
> +  payload: MessagePayload;
свойства надо описать

2020-11-19 17:01 UTC, neSpecc commented on src/types/message.ts
> +  workspaces?: Workspace[] | null;
это хардкод. По сути это типы либы Transport, тут не должно быть конкретных описаний пэйлоадов. Они должны быть где-то выше

2020-11-19 17:01 UTC, neSpecc commented on src/types/incomingMessage.ts
> +interface IncomingMessage extends RequestMessage {
не описан класс и свойства

2020-11-19 17:01 UTC, neSpecc commented on src/index.ts
> +server.on('connection', Server.connection);
это (и `new ws.Server...`) тоже должно быть убрано внутрь транспорта.

В точке входа должно остаться что-то типа:

```ts
this.transport = new Transport({ 
  endpoint: ''
});
```

2020-11-19 17:01 UTC, neSpecc commented on src/controllers/agent.ts
> +      clients?.forEach(client => Server.send(client.socket, null, { workspace }));
а где type? у каждого сообщения должен быть тип. И его формирование — это не задача Транспорта, в отличие от `messageId`. Его нужно взять из какой-то константы, которая лежит вне транспорта (тк это логика нашего приложения, а не либы Transport)

2020-11-19 17:01 UTC, neSpecc commented on src/utils/server.ts
> +  public static send(socket: ws, messageId: string | null, payload: object): void {
`messageId` — это внутренняя фича протокола, то есть она должна формироваться внутри, а не передаваться снаружи.

2020-11-19 17:01 UTC, neSpecc commented on src/utils/server.ts
> +    const workspaces = await WorkspacesService.find({ authToken });
протокол ничего не должен знать о воркспейсах и другой логике приложения

2020-11-19 17:01 UTC, neSpecc commented on src/utils/server.ts
> +    switch (dataObj.type) {
это явно не задача протокола (утилиты).

2020-11-20 19:44 UTC, neSpecc commented on src/utils/protocol/types/responseMessage.ts
> +  messageId: string | null;
тут не может быть null

2020-11-20 19:44 UTC, neSpecc commented on src/utils/protocol/types/responseMessage.ts
> +   * Message id, which we use to send response with this id (If API send message then messageId is null)
> (If API send message then messageId is null)

Это уже не ResponseMessage

2020-11-20 19:44 UTC, neSpecc commented on src/utils/protocol/messageCreator.ts
> +export default class MessageCreator {
давай избавимся от этого класса. Контроллеры не должны знать, какой тип сообщения они отправляют — то есть параметра `messageId` не должно быть. Формирование id сообщения это внутренняя логика транспорта. 

То есть лучше сделать в самом Transport.ts два отдельных метода: `send(type, payload)` (отправляет OutgoingMessage) и `respond(messageId, payload)`  (отравляет ResponseMessage)

2020-11-20 19:44 UTC, neSpecc commented on src/utils/protocol/transport.ts
> +  public static send(socket: ws, message: ResponseMessage | OutgoingMessage): void {
смущает что статик. Этот метод зависит от текущего инстанса, тк зависит от опций, переданных в конструктор. А раз зависит от инстанса, значит это не статик.

2020-11-20 19:44 UTC, neSpecc commented on src/controllers/agent.ts
> +      clients?.forEach(client => Transport.send(client.socket, MessageCreator.create(
такое ощущение, что Client — это тоже часть протокола. А значит передавать в send лучше `client` прямо, он знает что в нем есть `.socket`

2020-11-21 17:09 UTC, kebyo commented on src/utils/protocol/transport.ts
> +  public static send(socket: ws, message: ResponseMessage | OutgoingMessage): void {
Он статик, потому что в методе onmessage один из аргументов сокет this и я не знаю как вызвать по другому метод send, если внутри метода onmessage this это сокет.

2020-11-22 00:11 UTC, neSpecc commented on src/utils/protocol/transport.ts
> +    /**
wtf?

2020-12-10 16:38 UTC, merged