feat(proto): CodeX Transport Protocol
codex-team/devops-toolbox-api pull request #12
Opened 2020-11-29 00:53 UTC by neSpecc

Example of JavaScript implementation of the CodeX Transport Protocol

- see `/utils/ctproto/server.ts` for main protocol stuff.
- unit-testing of message validation and authorization

Example of protocol usage:

```ts
 req.app.locals.transport
  .clients
  .query((client: Client) => (client.authData as DevopsToolboxAuthData).workspaceIds.includes(workspace._id))
  .send('workspace-updated', { workspace });
```

This request is based on #10

2020-11-29 08:44 UTC, neSpecc commented on src/utils/ctproto/clientsList.ts
> +        this.clients.splice(index, 1);
todo : add the `.close()` method and call it before reving

2020-11-29 22:09 UTC, ilyamore88 reviewed
Выглядит круто, ещё бы протестить...

2020-11-29 22:09 UTC, ilyamore88 commented on README.md
> +1. Fill `.env` file with necessary values (see .env.sample)
У нас `.env.example`

2020-12-01 10:24 UTC, neSpecc commented on README.md
> +1. Fill `.env` file with necessary values (see .env.sample)
fixed

2020-12-01 16:55 UTC, nikmel2803 requested changes

2020-12-01 16:55 UTC, nikmel2803 commented on src/config/index.ts
> +declare const process : {
Вообще, правильнее это делать так
https://medium.com/javascript-in-plain-english/how-to-get-typescript-type-completion-by-defining-process-env-types-6a5869174f57

```ts
declare namespace NodeJS {
  export interface ProcessEnv {
    HOST: string;
    DB_URL: string;
    DB_NAME?: string;
  }
}
```

2020-12-01 16:55 UTC, nikmel2803 commented on src/config/index.ts
> +  public static wsPath: string = process.env.WS_PATH || '';
Давай лучше уберём параметры по дефолту

2020-12-01 16:55 UTC, nikmel2803 commented on src/index.ts
> +  // path: '/client',
Выпилить наверное надо
и из .env

2020-12-01 16:55 UTC, nikmel2803 commented on src/types/auth.ts
> +export type DevopsToolboxAuthRequest = {
А почему не интерфейс?

2020-12-01 16:55 UTC, nikmel2803 commented on src/types/workspaceConfig.ts
> +import { Workspace } from './workspace';
мне кажется, дефолтный красивее

2020-12-01 16:55 UTC, nikmel2803 commented on tsconfig.json
> +  },
в json же это ошибка

2020-12-01 16:55 UTC, nikmel2803 commented on src/utils/ctproto/messageValidator.ts
> +      if ((parsedMessage as unknown as PossibleInvalidMessage)[field] === undefined) {
может так будет проще?
![telegram-cloud-photo-size-2-5348506577843368163-y](https://user-images.githubusercontent.com/32655339/100770396-4662d200-340e-11eb-9915-4226a5c8157b.jpg)
И по типам правильнее

2020-12-01 16:55 UTC, nikmel2803 commented on src/utils/ctproto/clientsList.ts
> +export default class ClientsList {
Стоит сделать отдельный класс Cursor (примерно как при работе с mongodb, где метод `collection().find` возвращает объект Cursor

2020-12-01 16:59 UTC, nikmel2803 reviewed
+ вебшторм ругается на то, что много где вызываются асинхронные функции без обработчиков
если в каком нибудь выскочет ошибка, то будет неприятно, надо хотя бы .catch добавить

2020-12-01 17:16 UTC, neSpecc commented on src/config/index.ts
> +declare const process : {
fixed

2020-12-01 17:16 UTC, neSpecc commented on src/config/index.ts
> +  public static wsPath: string = process.env.WS_PATH || '';
fixed

2020-12-01 17:16 UTC, neSpecc commented on src/index.ts
> +  // path: '/client',
fixed

2020-12-01 17:16 UTC, neSpecc commented on src/types/auth.ts
> +export type DevopsToolboxAuthRequest = {
fixed

2020-12-01 17:16 UTC, neSpecc commented on src/types/workspaceConfig.ts
> +import { Workspace } from './workspace';
там могут быть и другие экспорты потом

2020-12-01 17:16 UTC, neSpecc commented on tsconfig.json
> +  },
fixed

2020-12-01 17:16 UTC, neSpecc commented on src/utils/ctproto/messageValidator.ts
> +      if ((parsedMessage as unknown as PossibleInvalidMessage)[field] === undefined) {
fixed

2020-12-01 17:17 UTC, neSpecc commented on src/utils/ctproto/clientsList.ts
> +export default class ClientsList {
давай отдельной задачей

2020-12-01 17:33 UTC, nikmel2803 commented on src/index.ts
> +  // path: '/client',
в .env.sample
<img width="406" alt="image" src="https://user-images.githubusercontent.com/32655339/100775576-85942180-3414-11eb-9c92-342cf6ca11ea.png">

2020-12-01 17:36 UTC, nikmel2803 commented on src/types/workspaceConfig.ts
> +import { Workspace } from './workspace';
ну главный экспорт из этого файла всё равно будет именно воркспейс, так что почему бы не сделать его дефолтным

2020-12-01 17:48 UTC, nikmel2803 commented on src/types/env.ts
> +}
а как же доки 🤔

2020-12-01 17:48 UTC, nikmel2803 commented on src/utils/ctproto/messageValidator.ts
> +      // eslint-disable-next-line valid-typeof
я убрал, линтер не ругался
вроде это не нужно

2020-12-01 19:28 UTC, kebyo commented on src/controllers/agent.ts
> +import { DevopsToolboxAuthData } from '../types/auth';
А почему ты не импортируешь `DevopsToolboxAuthData` из **'../types'**? Можно добавить весь `auth` в **/types/index.ts** и оттуда импортировать все

2020-12-01 19:28 UTC, kebyo commented on src/index.ts
> +import { NewMessage, AuthRequestPayload } from './utils/ctproto/types';
Тоже самое с импортами из '**./types'**

2020-12-01 19:28 UTC, kebyo commented on src/types/auth.ts
> +import { AuthData } from '../utils/ctproto/types/auth';
Импорт из **types** должен быть

2020-12-01 19:28 UTC, kebyo commented on src/utils/ctproto/server.ts
> +import MessageValidator from './messageValidator';
Может их запихнуть в папку типа `MessageService` и оттуда импортировать?

2020-12-02 13:25 UTC, kebyo commented on src/controllers/agent.ts
>          .send('workspace-updated', { workspace });
А почему тут не через `MessageFactory`?

2020-12-03 12:09 UTC, neSpecc commented on src/controllers/agent.ts
>          .send('workspace-updated', { workspace });
MessageFactory это внутренняя сущность протокола, снаружи о ней знать не нужно. И `send` теперь строго типизирован туда нельзя передать что попало. А `MessageFactory ` возвращает строку обычную

2020-12-03 12:23 UTC, neSpecc commented on src/utils/ctproto/server.ts
> +import MessageValidator from './messageValidator';
не вижу смысла пока усложнять и вводить новый термин service

2020-12-03 12:25 UTC, neSpecc commented on src/controllers/agent.ts
> +import { DevopsToolboxAuthData } from '../types/auth';
переделал

2020-12-03 12:25 UTC, neSpecc commented on src/utils/ctproto/messageValidator.ts
> +      // eslint-disable-next-line valid-typeof
убрал

2020-12-03 12:25 UTC, neSpecc commented on src/types/env.ts
> +}
добавил

2020-12-08 18:05 UTC, fabled228 approved these changes

2020-12-08 18:06 UTC, nikmel2803 commented on package.json
> +    "test:clear": "jest --clearCache",
точно нужно всегда удалять кэш?

2020-12-08 18:06 UTC, nikmel2803 commented on src/controllers/agent.ts
> +        .find((client: Client<DevopsToolboxAuthData, ApiResponse, ApiOutgoingMessage>) => client.authData.workspaceIds.includes(workspace._id))
если всё правильно типизировано, то в find не надо же указывать тип

2020-12-08 18:06 UTC, nikmel2803 commented on src/controllers/workspaces.ts
> +    console.log('getWorkspaces request payload: ', message);
лог нужен?

2020-12-08 18:06 UTC, nikmel2803 commented on tsconfig.json
> +    "strict": true,
```suggestion
    "strict": true
```

2020-12-08 18:07 UTC, neSpecc commented on package.json
> +    "test:clear": "jest --clearCache",
почему всегда? это вспомогательная команда

2020-12-08 18:07 UTC, neSpecc commented on src/controllers/agent.ts
> +        .find((client: Client<DevopsToolboxAuthData, ApiResponse, ApiOutgoingMessage>) => client.authData.workspaceIds.includes(workspace._id))
надо, иначе будет неявный any-тип

2020-12-08 18:09 UTC, neSpecc commented on src/controllers/workspaces.ts
> +    console.log('getWorkspaces request payload: ', message);
убрал

2020-12-08 18:09 UTC, neSpecc commented on tsconfig.json
> +    "strict": true,
убрал

2020-12-08 19:11 UTC, ilyamore88 approved these changes

2020-12-08 22:58 UTC, nikmel2803 commented on package.json
> +    "test:clear": "jest --clearCache",
а, я слепой

2020-12-08 23:01 UTC, nikmel2803 commented on src/controllers/agent.ts
> +        .find((client: Client<DevopsToolboxAuthData, ApiResponse, ApiOutgoingMessage>) => client.authData.workspaceIds.includes(workspace._id))
потому что в locals нет типизации
замени на context и всё будет вкусно
<img width="635" alt="image" src="https://user-images.githubusercontent.com/32655339/101551641-62441600-39c2-11eb-8439-617109b915f4.png">

2020-12-09 21:25 UTC, nikmel2803 approved these changes

2020-12-10 16:38 UTC, merged