Changed workspaceIds to workspaces
codex-team/devops-toolbox-api pull request #19
Opened 2021-01-15 18:10 UTC by kebyo

Мы должны отправить в приложение данные о воркспейсе, а не его _id

2021-01-15 19:39 UTC, ilyamore88 requested changes
Пофикси линтер.

2021-01-15 19:39 UTC, ilyamore88 commented on src/index.ts
> +    console.log(message);
Лишний log

2021-01-15 19:39 UTC, ilyamore88 commented on src/controllers/agent.ts
> +        .find((client) => client.authData.workspaces.filter(w => w._id.toString() === workspace._id.toString()).length > 0)
А что означает `.length > 0`? Мы можем получить несколько воркспейсов после `.filter`? Кажется нет. Кажется, надо использовать `.find` вместо `.filter`.

2021-01-19 14:49 UTC, ilyamore88 approved these changes

2021-01-19 17:58 UTC, neSpecc commented on src/types/api/responses/authorize.ts
>     * Owned workspaces ids
```suggestion
   * Owned workspaces
```

2021-01-20 18:35 UTC, neSpecc approved these changes

2021-01-21 09:25 UTC, merged