Feature/creating workspaces in database
codex-team/devops-toolbox-api pull request #4
Opened 2020-11-02 18:38 UTC by Xemka

1. Добавил модель и пример конфиг-файла воркспейсов
2. Добавил функциональность для считывания данных о воркспейсах из .yml файла и сохранения их в базе данных

2020-11-03 14:12 UTC, nikmel2803 requested changes

2020-11-03 14:12 UTC, nikmel2803 commented on src/workspaces.ts
> +    const url = 'mongodb+srv://xema:wCyPjqzoe7JRiGUX@cluster0.nxtjs.mongodb.net/workspaces';
эта строчка должна из .env подгружаться

2020-11-03 14:12 UTC, nikmel2803 commented on src/workspaces.ts
> + * Send workspace information to database
Сначала описание функции, а потом @param

2020-11-03 14:12 UTC, nikmel2803 commented on src/workspaces.ts
> +  const file = fs.readFileSync('./workspaces.yml', 'utf-8');
думаю лучше чтобы имя этого файлы тоже подгружалось из .env
по умолчанию его поставить, например ./config.yml

2020-11-03 14:12 UTC, nikmel2803 commented on yml.example
> +workspaces:
лучше назвать config.example.yml

2020-11-04 13:25 UTC, nikmel2803 requested changes

2020-11-04 13:25 UTC, nikmel2803 commented on src/config/config.yml
> +workspaces:
нужно оставить только config.example.yml в репозитории, а сам конфиг в игнор добавить

2020-11-04 13:25 UTC, nikmel2803 commented on src/index.ts
> +    console.log(data);
кажется ты как-то неправильно смержил код
ты убрал фичи, которые пилил Ойбек

2020-11-04 13:25 UTC, nikmel2803 commented on src/models/workspace.ts
> +module.exports = model('Workspace', workspace);
export default

2020-11-04 13:25 UTC, nikmel2803 commented on src/models/workspace.ts
> +});
не помешала бы документация...
а Ойбек же пилил тоже модель воркспейса 🤔

2020-11-04 13:25 UTC, nikmel2803 commented on src/workspaces.ts
> + * @param url
параметр бы описать

2020-11-04 13:25 UTC, nikmel2803 commented on src/workspaces.ts
> + * @param workspace
и тут бы параметр описать

2020-11-04 13:25 UTC, nikmel2803 commented on src/workspaces.ts
> +function saveWorkspace(workspace: any): void {
any надо бы чем-то более конкретным заменить

2020-11-04 13:34 UTC, Xemka commented on src/models/workspace.ts
> +});
у него была идентичная модель, но без authToken'a

2020-11-04 13:42 UTC, Xemka commented on src/models/workspace.ts
> +});
Да, она оказывается была в другой папке. Уберу свою тогда и буду пользоваться его моделью.

2020-11-04 15:51 UTC, nikmel2803 commented on src/workspaces.ts
> +  workspaces.forEach((item: any) => {
в typescript надо избегать any и использовать его только там, где это точно необходимо и ты не знаешь что там будет за тип. А в нашем случае ты знаешь структуру конфига и можешь описать её в интерфейсе

```ts
interface ConfigData {
  workspaces: WorkspacesConfigData[]
}
```
и написать `YAML.parse(file) as ConfigData `
тогда появится и типизация и можно будет any тут опустить

2020-11-04 15:51 UTC, nikmel2803 commented on src/workspaces.ts
> +function saveWorkspace(workspace: any): void {
Тут у тебя же приходит модель воркспейса. Так вот и напиши сюда Workspace вместо any

2020-11-04 15:51 UTC, nikmel2803 commented on src/workspaces.ts
> +    console.log(e);
думаю, тут можно сделать ещё и return
какой смысл функции работать дальше, если нет подключения к бд

2020-11-05 17:35 UTC, nikmel2803 commented on src/workspaces.ts
> +import { type } from "os";
лишний импорт

2020-11-05 18:37 UTC, nikmel2803 approved these changes

2020-11-05 18:38 UTC, neSpecc requested changes

2020-11-05 18:38 UTC, neSpecc commented on src/config/index.ts
> +  public static wsUrl: string = process.env.CONFIG_FILE! || '../config.yml';
странное название wsUrl. Особенно с учетом что выше есть wsPort

2020-11-05 18:38 UTC, neSpecc commented on src/types/workspaceConfig.ts
> +  workspaces: Workspace[];
не описано

2020-11-05 18:43 UTC, Xemka commented on src/config/index.ts
> +  public static wsUrl: string = process.env.CONFIG_FILE! || '../config.yml';
тут wsPort == webSocket Port, а wsUrl == workspaces Url (url конфиг файла с воркспейсами)

2020-11-06 18:22 UTC, neSpecc commented on src/config/index.ts
> +  public static wsUrl: string = process.env.CONFIG_FILE! || '../config.yml';
да, это меня и смущает. Давай назовём `workspacesConfgPath` или типа того

2020-11-06 19:08 UTC, neSpecc approved these changes

2020-11-06 19:41 UTC, merged